# Generated by Django 2.2 on 2019-07-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
